[project]
name = "pyproj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "brevitas>=0.12.1",
    "torch>=2.10.0",
    "torchvision>=0.25.0",
]
